### ISSUE TITLE
Uncaught TypeError: Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by randomblast** [Nickforall/atom-racer#2]
1. Put cursor on `Iterator` word in a valid Rust file
2. Press F3 to go to definition

Rust source directory setting is correctly configured to point to my rustup's checkout of the stable sources. Racer is installed in ~/.cargo/bin

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: [racer-v2](https://github.com/Nickforall/atom-racer) package 2.1.1

### Stack Trace

Uncaught TypeError: Cannot read property 'toLowerCase' of undefined

```
At /Users/Josh/.atom/packages/racer-v2/lib/racer.coffee:85

TypeError: Cannot read property 'toLowerCase' of undefined
    at /packages/racer/lib/racer.coffee:85:42
    at options.exit (/packages/racer-v2/lib/racer-client.coffee:38:11)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:338:1)
    at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:368:1)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

### Commands

```
     -1:17.8.0 autocomplete-plus:confirm (input.hidden-input)
     -1:16.4.0 editor:select-to-beginning-of-word (input.hidden-input)
     -1:15.3.0 autocomplete-plus:cancel (input.hidden-input)
  2x -1:14.8.0 editor:newline (input.hidden-input)
  6x -1:08.0 core:backspace (input.hidden-input)
  5x -1:00.0 editor:move-to-beginning-of-word (input.hidden-input)
     -0:55.8.0 core:backspace (input.hidden-input)
     -0:54.1.0 editor:move-to-end-of-screen-line (input.hidden-input)
  5x -0:46.7.0 core:move-left (input.hidden-input)
     -0:45.5.0 core:backspace (input.hidden-input)
  3x -0:45.3.0 core:move-right (input.hidden-input)
     -0:43.6.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -0:31.4.0 core:move-down (input.hidden-input)
     -0:30.2.0 core:move-up (input.hidden-input)
     -0:29.9.0 editor:newline (input.hidden-input)
  2x -0:14.2.0 racer:find-definition (input.hidden-input)
```

### Non-Core Packages

```
build 0.68.0 
build-cargo 2.0.0 
busy 0.7.0 
cargo-test-runner 0.1.0 
dash 1.7.1 
haskell-grammar 0.4.0 
highlight-selected 0.13.1 
language-babel 2.65.1 
language-graphql 0.9.0 
language-ini 1.19.0 
language-lua 0.9.11 
language-ocaml 1.9.5 
language-rust 0.4.10 
language-swift 0.5.0 
language-thrift 1.0.2 
MagicPython 1.0.10 
merge-conflicts 1.4.5 
nuclide 0.232.0 
nuclide-format-js 0.0.36 
racer-v2 2.1.1 
set-syntax 0.3.2 
sort-lines 0.14.0 
tool-bar 1.1.0 
```

**Comment by Nickforall** [comment]
Fixed in d750873.
